name: Deploy Node.js App

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      #  Setup SSH
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ANSIBLE_KEY }}
          
      - name: Copy app to server
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<EC2_PUBLIC_IP> "mkdir -p ~/app"
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ec2-user@<EC2_PUBLIC_IP>:~/app

      - name: Install and start app
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@<EC2_PUBLIC_IP> "
            cd ~/app &&
            npm install &&
            pm2 restart app || pm2 start index.js --name app
          "
